### ISSUE TITLE
Adres sözünü ünvan kimi tərcümə edə bilərikmi?

### ISSUE THREAD

**Issue by Komport** [AzePUG/Data_Structures_Algo_Python#21]
Mətndə istifadə olunan "adres" sözünü "ünvan" kimi tərcümə olunması məncə daha məqsədə uyğun olar.

**Comment by ShahriyarR** [comment]
Olar əlbəttə.
Yaddaş ünvanı sözü qulağa  xoş gəlirmi?
Əgər gəlirsə, dəyişib PR ata bilərsən?

**Comment by ShahriyarR** [comment]
#22 PR-a esasen baglayiram bu issue-nu.
