### ISSUE TITLE
Dövri Əlaqəli listlər - 185-ci sətr

### ISSUE THREAD

**Issue by Komport** [AzePUG/Data_Structures_Algo_Python#39]
Dövri Əlaqəli listlər bölümündə 185-ci sətrdə olan cümləni tam olaraq anlamadım.  Çöx güman ya yarımçıq ya da artıq sözlər düşüb. 

```
# Hal-hazırkı tapılan node-u isə yeni head-ə yönləndiririk və yaxud yeni head-ə
```

**Comment by ShahriyarR** [comment]
Düzdür.
`# Hal-hazırkı tapılan node-u isə yeni head-ə yönləndiririk və yaxud yeni head-ə` əvəzinə 
`# Hal-hazırkı tapılan node-u isə yeni head-ə və yaxud yeni node-a yönləndiririk.` şəklində olmalıdır.

**Comment by ShahriyarR** [comment]
@Komport PR atmaq isteyirsense at :)

**Comment by Komport** [comment]
Atdım PR - fix_for_issue#39
