### ISSUE TITLE
Giriş-də qrammatik səhv - primitiv əvəzinə primit yazılıb

### ISSUE THREAD

**Issue by IsmayilAliyev** [AzePUG/Data_Structures_Algo_Python#63]
Burda mence primitiv yazmaq istemisiz.

![image](https://user-images.githubusercontent.com/29096800/45473819-1b1a3c80-b749-11e8-8a3f-97b4ca3fc6a0.png)

**Comment by ShahriyarR** [comment]
Giriş-də:
https://azepug.gitbooks.io/data-strukturlari-v-alqoritml-r/content/book/1.Giri%C5%9F.html

**Comment by ShahriyarR** [comment]
@IsmayilAliyev özünüz düzəlişlər edib PR ata bilərsinizmi?
