### ISSUE TITLE
Sructures sözünü Structures sözilə əvəz etmək lazimdir.

### ISSUE THREAD

**Issue by IsmayilAliyev** [AzePUG/Data_Structures_Algo_Python#64]
![image](https://user-images.githubusercontent.com/29096800/45474569-279f9480-b74b-11e8-9cba-991683bf3ab1.png)

**Comment by ShahriyarR** [comment]
Giriş-də 1.3-ə aid olan qrammatik səhv.
https://azepug.gitbooks.io/data-strukturlari-v-alqoritml-r/content/book/1.Giri%C5%9F.html

**Comment by ShahriyarR** [comment]
@IsmayilAliyev özünüz düzəlişlər edib PR ata bilərsinizmi?

**Comment by IsmayilAliyev** [comment]
Hec vaxt aatmamsam.baxim gorum alinsa elbette ataram.

**Comment by ShahriyarR** [comment]
@IsmayilAliyev 
Fork edin bu repo-nu daha sonra öz fork etdiyiniz repo-nu clone edin local maşınınıza.
Orada dəyişiklik edib push edin fork-unuza.
Ordan da Pull Request yaradın bu əsas repo-ya.
