### ISSUE TITLE
Giriş faylında "girdi" ifadəsi

### ISSUE THREAD

**Issue by Maharramoff** [AzePUG/Data_Structures_Algo_Python#69]
**Açıqlama**
- Dəyişmədim. Dedim öncə müzakirə edək. Azərbaycan dilində belə bir ifadə olduğunu düşünmürəm.  [Giriş.md#L130](https://github.com/AzePUG/Data_Structures_Algo_Python/blame/master/book/1.Giri%C5%9F.md#L130)

**Təklif**
- Daxiletməyə əsasən...
- Daxil edilmiş informasiyaya əsasən...
- Girişə əsasən...
- Və ya sadəcə input saxlamaq olar.

**Skrinlər**
![girdi](https://user-images.githubusercontent.com/9804406/54167464-34474000-4483-11e9-86f3-d21238c8050c.png)

**Comment by ShahriyarR** [comment]
İnput olaraq saxlayaq. Mötərizədə isə əlavə izah verək:
input(daxil edilmiş informasiyaya əsasən) - belə sizcə uyğundur?

**Comment by ShahriyarR** [comment]
Yaxşı fikirdir. Bunu etməkdə köməklik edərsinizmi?
Bu PR çox möhtəşəm irəliləyiş olar :)
